version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.4-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build-datatable

      - run:
          name: Copy README and LICENSE
          command: |
            cp LICENSE dist/ng-datatable/
            cp README.md dist/ng-datatable/

      - store_artifacts:
          path: dist/ng-datatable

      - deploy:
          command: |
            echo "${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              yarn ci-publish
            else
              echo "Only the production branch is published"
            fi
