name: Build
run-name: Build

on:
    push:

jobs:
    build:
        name: Build NPM Project
        runs-on: ubuntu-latest
        container: node:8
        steps:
            -   name: Clone Repository
                uses: ztimson/actions/clone@develop

            -   name: Install Dependencies
                run: npm i

            -   name: Build Project
                run: npm run build

            -   name: Upload Artifacts
                uses: actions/upload-artifact@v3
                with:
                    path: dist
                    retention-days: 7

            -   name: Push to registry
                if: ${{github.ref_name}} == "production"
                uses: ztimson/actions/npm/publish@develop

    tag:
        name: Tag Version
        needs: build
        runs-on: ubuntu-latest
        container: node:8
        steps:
            -   name: Clone Repository
                uses: ztimson/actions/clone@develop

            -   name: Get Version Number
                run: echo "VERSION=$(cat package.json | grep version | grep -Eo ':.+' | grep -Eo '[[:alnum:]\.\/\-]+')" >> $GITHUB_ENV

            -   name: Tag Version
                uses: ztimson/actions/tag@develop
                with:
                    tag: ${{env.VERSION}}
